# Configuration parameters

[general]
address = "127.0.0.1"
port = 8080
port_tls = 443
certificate = ["misc/server.crt", "misc/server.key"]

[token]
secret_key = "" # don't leave this empty
expiration = 5 # in minutes
