# Configuration parameters

[general]
logpath = "misc/netchat.log"
testuser = ["test", "<hash>"] # generated during init mode

[backend]
address = "127.0.0.1"
port = 8080
port_tls = 1025
certificate = ["misc/server.crt", "misc/server.key"]

[token]
secretkey = "" # used as salt for password generation
expiration = 5 # in minutes

[mysql]
user = ""
password = ""
address = "192.168.0.2"
port = 3306
timeout = 3
database = ""
table = "history"
